script: "bundle exec rake test"
rvm:
  - 1.8.7
  - jruby-18mode
  - 1.9.3
  - jruby-19mode
  - 2.0.0
  - 2.1.1
  - rbx-2
gemfile:
  - gemfiles/Gemfile.rails-3.0.x
  - gemfiles/Gemfile.rails-3.1.x
  - gemfiles/Gemfile.rails-3.2.x
  - Gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
  allow_failures:
    - rvm: rbx-2
